spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/patientdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    root: info